-- AlterTable
ALTER TABLE "line_items" ALTER COLUMN "bookedAmount" SET DATA TYPE DECIMAL(20,15),
ALTER COLUMN "actualAmount" SET DATA TYPE DECIMAL(20,15),
ALTER COLUMN "adjustments" SET DATA TYPE DECIMAL(20,15);
